#!/bin/bash

set -u

basedir=$1

# bootstrap base debian system
debootstrap stable $basedir

# enable autologin for root
mkdir -p $basedir/etc/systemd/system/console-getty.service.d
cat << EOF > $basedir/etc/systemd/system/console-getty.service.d/override.conf
[Service]
ExecStart=
ExecStart=-/sbin/agetty --noclear --autologin root --keep-baud console 115200,38400,9600 $TERM
EOF

# mock out waggle init
mkdir -p $basedir/etc/systemd/system/waggle-init.service.d
cat << EOF > $basedir/etc/systemd/system/waggle-init.service.d/override.conf
[Service]
ExecStart=
ExecStart=-/bin/true
EOF

# mock out hosts
cat << EOF > $basedir/etc/hosts
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
10.10.10.5 beehive
EOF

# mock out hbmode
cat << EOF > $basedir/etc/waggle/hbmode
wellness
EOF

# copy mocked out services
cp bin/* $basedir/bin

# ensure waggle image packages are installed
systemd-nspawn -D $basedir bash -s << EOF
useradd -m -p waggle waggle

apt-get update && apt-get install -y \
  git \
  curl \
  socat \
  usbutils \
  net-tools \
  python3 \
  python3-pip \
  openssh-server \
  autossh \
  rabbitmq-server

# notes:
# rabbitmq-server needs socat, but doesn't seem to install it automatically

pip3 install \
  git+https://github.com/waggle-sensor/pywaggle \
  zmq

mkdir -p /wagglerw/waggle

mkdir -p /wagglerw/plugins
chmod 700 /wagglerw/plugins

# need v2 branch???
mkdir -p /usr/lib/waggle

cd /usr/lib/waggle
git clone https://github.com/waggle-sensor/core
cd core
./configure

cd /usr/lib/waggle
git clone https://github.com/waggle-sensor/nodecontroller
cd nodecontroller
./configure

cd /usr/lib/waggle
git clone https://github.com/waggle-sensor/plugin_manager
cd plugin_manager
./configure
EOF

# TODO rabbitmq-server should install from more up to date repo
# add waggle-init override

# remove shutdown when wagman connected
# rm $basedir/etc/systemd/system/waggle-core.target.wants/waggle-monitor-shutdown.service
