#!/bin/bash

set -u

basedir=$1

# bootstrap base debian system
debootstrap stable $basedir

# enable autologin for root
mkdir -p $basedir/etc/systemd/system/console-getty.service.d
cat << EOF > $basedir/etc/systemd/system/console-getty.service.d/override.conf
[Service]
ExecStart=
ExecStart=-/sbin/agetty --noclear --autologin root --keep-baud console 115200,38400,9600 $TERM
EOF

# mock out waggle init
mkdir -p $basedir/etc/systemd/system/waggle-init.service.d
cat << EOF > $basedir/etc/systemd/system/waggle-init.service.d/override.conf
[Service]
ExecStart=
ExecStart=-/bin/true
EOF

# ensure waggle image packages are installed
systemd-nspawn -D $basedir bash -s << EOF
apt-get update && apt-get install -y \
  git \
  python3 \
  python3-pip \
  openssh-server \
  rabbitmq-server

pip3 install \
  git+https://github.com/waggle-sensor/pywaggle \
  zmq

mkdir -p /wagglerw

# need v2 branch???
mkdir -p /usr/lib/waggle

cd /usr/lib/waggle
git clone https://github.com/waggle-sensor/core
cd core
./configure

cd /usr/lib/waggle
git clone https://github.com/waggle-sensor/nodecontroller
cd core
./configure

cd /usr/lib/waggle
git clone https://github.com/waggle-sensor/plugin_manager
cd core
./configure
EOF

# TODO rabbitmq-server should install from more up to date repo
# add waggle-init override
